name = "bookshell-website"
main = "worker.js"
compatibility_date = "2026-05-29"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
WAITLIST_TAG = "bookshell-early-access"

[[d1_databases]]
binding = "bookshell_waitlist"
database_name = "bookshell_waitlist"
database_id = "07d869f7-ec3e-4359-88f7-6d0757152202"
